import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {contentFingerprint,normalizeTextValue,stableJson} from '../src/services/content-normalizer.js';
import {canTransition,assertTransition} from '../src/services/conversation-state-machine.js';
const root=new URL('../',import.meta.url);
const read=p=>fs.readFileSync(new URL(p,root),'utf8');
const service=read('src/services/content-service.js');
const routes=read('src/routes/modular-api.js');
const conflicts=read('src/services/content-conflict-service.js');
const engine=read('src/engine.js');
const server=read('src/server.js');
const migrations=read('src/services/modular-migrations.js');
const conv=read('public/assets/js/pages/conversations.js');
const canned=read('public/assets/js/pages/canned-responses.js');
const aiSettings=read('public/assets/js/pages/ai-settings.js');

test('01 normalize whitespace',()=>assert.equal(normalizeTextValue('  A   B\r\nC  '),'A B\nC'));
test('02 stable json key order',()=>assert.equal(stableJson({b:1,a:2}),stableJson({a:2,b:1})));
test('03 fingerprint is deterministic',()=>assert.equal(contentFingerprint('knowledge',{title:'A'}),contentFingerprint('knowledge',{title:'A'})));
test('04 fingerprint ignores case for string content',()=>assert.equal(contentFingerprint('knowledge',{title:'ABC'}),contentFingerprint('knowledge',{title:'abc'})));
test('05 different collections produce different fingerprints',()=>assert.notEqual(contentFingerprint('knowledge',{title:'a'}),contentFingerprint('responses',{title:'a'})));
test('06 knowledge CRUD route',()=>assert.match(routes,/content\/\$\{name\}.*createRecord/s));
test('07 knowledge export route',()=>assert.match(routes,/content\/\$\{name\}\/export/));
test('08 knowledge import route',()=>assert.match(routes,/content\/\$\{name\}\/import/));
test('09 duplicate reject implemented',()=>assert.match(service,/DUPLICATE_REJECTED/));
test('10 partial duplicate counters implemented',()=>assert.match(service,/duplicateSkipped:duplicate/));
test('11 delete all requires typed confirmation',()=>assert.match(routes,/CONFIRMATION_REQUIRED/));
test('12 responses table separate from canned',()=>assert.match(migrations,/CREATE TABLE IF NOT EXISTS bot_manual_responses/));
test('13 responses retrieved by dedicated service',()=>assert.match(engine,/getRelevantBotResponses/));
test('14 canned not injected into AI response source',()=>assert.match(engine,/humanCannedRows.*never injected into AI prompt/s));
test('15 rules have priority',()=>assert.match(migrations,/ai_rules ADD COLUMN IF NOT EXISTS priority/));
test('16 rules have stop processing',()=>assert.match(migrations,/stop_processing BOOLEAN/));
test('17 conflict detector compares conditions',()=>assert.match(conflicts,/conditionKey\(a\)!==conditionKey\(b\)/));
test('18 conflict detector does not auto delete',()=>assert.doesNotMatch(conflicts,/DELETE FROM ai_rules/));
test('19 important import export uses shared engine',()=>assert.match(routes,/\['knowledge','responses','rules','important','supplies'\]/));
test('20 supplies import export uses shared engine',()=>assert.match(service,/name==='supplies'/));
test('21 content import uses transaction',()=>assert.match(service,/client\.query\('BEGIN'\)/));
test('22 fatal import rolls back',()=>assert.match(service,/client\.query\('ROLLBACK'\)/));
test('23 import history exists',()=>assert.match(migrations,/content_import_history/));
test('24 data versioning exists',()=>assert.match(migrations,/content_collection_meta/));
test('25 sync all bumps all collections',()=>assert.match(service,/syncAllCollections/));
test('26 sync all endpoint exists',()=>assert.match(routes,/\/sync\/all/));
test('27 AI active to human allowed',()=>assert.equal(canTransition('AI_ACTIVE','HUMAN_TAKEOVER'),true));
test('28 human to AI allowed',()=>assert.equal(canTransition('HUMAN_TAKEOVER','AI_ACTIVE'),true));
test('29 closed is terminal',()=>assert.equal(canTransition('CLOSED','AI_ACTIVE'),false));
test('30 invalid transition throws',()=>assert.throws(()=>assertTransition('CLOSED','AI_ACTIVE'),/INVALID_CONVERSATION_STATE_TRANSITION/));
test('31 DB state column has required states',()=>{for(const x of ['AI_ACTIVE','HUMAN_TAKEOVER','WAITING_TELEGRAM','PROCESSING','CLOSED'])assert.match(migrations,new RegExp(x))});
test('32 takeover updates explicit state',()=>assert.match(read('src/db.js'),/handling_state='HUMAN_TAKEOVER'/));
test('33 return AI updates explicit state',()=>assert.match(read('src/db.js'),/handling_state='AI_ACTIVE'/));
test('34 end chat updates explicit state',()=>assert.match(read('src/db.js'),/handling_state='CLOSED'/));
test('35 conversations composer requires takeover',()=>assert.match(conv,/composer\.disabled=.*HUMAN/));
test('36 canned autocomplete reacts to hash token',()=>assert.match(conv,/match\(\/\(\?:\^\|\\s\)\(#[^\n]+/));
test('37 canned keyboard navigation implemented',()=>{for(const k of ['ArrowDown','ArrowUp','Escape'])assert.match(conv,new RegExp(k))});
test('38 canned selection does not auto send',()=>{const choose=conv.slice(conv.indexOf('function choose'),conv.indexOf('composer.oninput'));assert.doesNotMatch(choose,/send\(/)});
test('39 canned page writes manual responses',()=>assert.match(canned,/\/api\/canned\/manual/));
test('40 sync all UI is wired to backend',()=>assert.match(aiSettings,/\/api\/sync\/all/));
test('41 conflict scan UI is wired',()=>assert.match(aiSettings,/\/api\/conflicts\/scan/));
test('42 direct routes are registered',()=>{for(const p of ['ai-settings','conversations','knowledge','responses','ai-rules','canned-responses','telegram-cta','telegram-settings','case-management','learning','menu-penting','bekal-bot','logs','security'])assert.match(server,new RegExp(`'${p}'`));assert.match(server,/app\.get\('\/system-health'/);assert.match(server,/app\.get\('\/health'/)});
test('43 direct route files exist',()=>{for(const p of ['ai-settings','conversations','knowledge','responses','ai-rules','canned-responses','telegram-cta','telegram-settings','case-management','learning','menu-penting','bekal-bot','logs','health','security'])assert.equal(fs.existsSync(new URL(`public/pages/${p}.html`,root)),true)});
test('44 modular css is split',()=>{for(const f of ['base.css','layout.css','components.css','forms.css','tables.css','conversations.css','responsive.css','theme.css'])assert.equal(fs.existsSync(new URL(`public/assets/css/${f}`,root)),true)});
test('45 modular js is split',()=>{for(const f of ['core/api.js','core/ui.js','core/shell.js','pages/ai-settings.js','pages/conversations.js','pages/content-page.js'])assert.equal(fs.existsSync(new URL(`public/assets/js/${f}`,root)),true)});
