import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const read=p=>fs.readFileSync(new URL('../'+p,import.meta.url),'utf8');
const server=read('src/server.js'),conv=read('public/assets/js/pages/conversations.js'),html=read('public/pages/conversations.html'),css=read('public/assets/css/conversations.css'),shell=read('public/assets/js/core/shell.js'),migration=read('src/services/modular-migrations.js');
test('conversation list uses server-side pagination and bounded limit',()=>{assert.match(server,/limit\|\|50/);assert.match(server,/nextOffset/);assert.match(conv,/limit:'50'/);assert.match(conv,/loadMoreChats/)});
test('message history uses cursor pagination and preserves older scroll',()=>{assert.match(server,/beforeId/);assert.match(server,/id<\$3/);assert.match(conv,/loadOlder/);assert.match(conv,/scrollHeight-oldHeight/)});
test('polling has latest-request-wins abort and adaptive background schedule',()=>{assert.match(conv,/listActive/);assert.match(conv,/active\.controller\.abort/);assert.match(conv,/reason==='poll'/);assert.match(conv,/document\.hidden/);assert.match(conv,/15000/);assert.match(conv,/pollDelay/)});
test('conversation actions expose loading state and state-specific buttons',()=>{assert.match(conv,/Taking Over\.\.\./);assert.match(conv,/Returning\.\.\./);assert.match(conv,/Ending\.\.\./);assert.match(conv,/classList\.toggle\('hidden',human/)});
test('canned shortcut remains human composer behavior and never auto sends',()=>{assert.match(conv,/chooseShortcut/);assert.match(conv,/composer\.disabled/);{const x=conv.slice(conv.indexOf('function chooseShortcut'),conv.indexOf('composer.oninput'));assert.doesNotMatch(x,/send\(/)}});
test('professional sidebar grouping and collapse exist',()=>{for(const x of ['OPERATIONS','BOT BRAIN','HUMAN TOOLS','INTEGRATIONS','SYSTEM'])assert.match(shell,new RegExp(x));assert.match(shell,/sidebar\.compact/);assert.match(shell,/Telegram/)});
test('conversation responsive structure keeps composer and detail drawer',()=>{for(const x of ['composer-shell','customer-panel','info-toggle','chat-open'])assert.match(html+css,new RegExp(x));assert.match(css,/@media\(max-width:820px\)/)});
test('performance indexes cover inbox and cursor message access',()=>{assert.match(migration,/idx_conversations_inbox_order/);assert.match(migration,/idx_messages_chat_id_desc/)})
