import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const ai=fs.readFileSync(new URL('../src/ai.js',import.meta.url),'utf8');
const engine=fs.readFileSync(new URL('../src/engine.js',import.meta.url),'utf8');
const db=fs.readFileSync(new URL('../src/db.js',import.meta.url),'utf8');
test('AI prompt requires chronological context digestion',()=>{ assert.match(ai,/Jangan menjawab hanya dari pesan terakhir/); assert.match(ai,/RINGKASAN KONTEKS LAMA/); });
test('long chats digest full stored history and keep recent context',()=>{ assert.match(engine,/recentLimit=60/); assert.match(engine,/getContextSlice/); assert.match(engine,/digestConversation/); });
test('human CS learning stores context snapshot and style examples',()=>{ assert.match(db,/context_snapshot/); assert.match(db,/getHumanStyleExamples/); assert.match(engine,/csStyleExamples/); });
test('unclear cases route silently to staff',()=>{ assert.match(ai,/gunakan ESCALATE_HUMAN dan reply kosong/); assert.match(engine,/silent_wait_staff/); });
